name: teek_flutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mockito: ^5.4.2
  stacked_generator: ^1.5.1

flutter:
  uses-material-design: true
